### PR TITLE
Targeting Bugfix

### LINKED ISSUE #8: BUG | NUJAS Dynamic Targeting Component
## 🐛 Bug Report

The Dynamic Targeting component loses sight of enemies as the desired rotation to each individual enemy is not considered based on weights.

## To Reproduce

1. Play the wolf demo
2. Try strafing left or right continuously in front of more than 1 enemy
3. As you move, the enemies in the front do not get increased rotational focus as opposed to enemies in the back so the enemies in the front can be lost out of sight

## Logs or Screenshots
[Line of code](https://github.com/nujas/TheJanusFramework/blob/master/Source/NujasCombat/Private/DynamicTargetingComponent.cpp#L123) that starts the calculate for the offset
```C++
if(AActor* const ClosestActor = FindClosestTargetOnScreen())
```

## Proposed Solution

Calculate a desired orientation to each enemy individually and merge the results together based on the weight of the targets. Based on the conversation with the SM team:

> We use basically everything as weights - position relative to player, to camera, velocity, combat target prioritization, likeliness to attack, everything. The key is to build a compromise rotation for each target, not to focus on any individual one or it starts to snap and pop. The weights being smooth is important, they're derived in ways that are mostly smooth and continuous to avoid pops and kicks. Effectively removing noise at the input stage is easier than doing it post-output. Some weights are laggy, but usually those are ones we barely care about. For example, boolean tests get converted into thermometers, which heats up if the test is true and cools down when false. Also, use the weights not just to drive the rotations about an individual enemy, but also how important each character is to the final blended rotation

Keep in mind that the weight are used for these purposes:
- to determine the priority of the enemy, meaning after x amount of enemies no more should be considered
- to calculate the orientation blend

### PR DESCRIPTION
**Pull request by DennisSSDev**
## Issues resolved:
The targeting component will now accurately focus on the enemy with an offset from the centre of the screen.

Currently works with only 1 enemy without weights integrated. So **no merges for now**

Working on testing for the offset validity, as the projection appears behind the target occasionally, meaning that the offset is sometimes conditional.

- [ ] closes #8 

## Test 

Visual Debug [here](https://www.youtube.com/watch?v=wtzwN3eiKEg)

Follow the red line. It signifies the centre of the screen and is drawn towards the enemy. The camera will attempt to interpolate and keep up with the enemy as it moves around.

## Demo

You can view the final result of the targeting system visualized [here](https://youtu.be/HIgb63T-4BQ)

### CODE REVIEW

**Comment by DennisSSDev** [comment]
# PR Done - Ready For Review
- Added more improvements to the targeting and it should now be already a step up from the previous version. The camera will pivot around the target, aka - using the camera central offset to the enemy. 
- The weights + other target recognition will be added as a separate bug report and a separate PR for it as well. 
- for now, it'll focus on only one enemy at a time which is like the old system, but with much more accurate targeting.

The current progress can be viewed [here](https://youtu.be/HIgb63T-4BQ)

**Comment by DennisSSDev** [comment]
The tests are represented through the debug drawing of the lines from the targets to the camera. 
Once the PR is approved I would like to get a note on where to put the tests.

My thought is that we can just put them in a `#ifdef` clause and not compile them once creating a staging / production build.

File: Source/NujasCombat/Private/DynamicTargetingComponent.cpp [hunk 1]
```diff
@@ -118,63 +120,79 @@ void UDynamicTargetingComponent::UpdateCameraLock()
...
-	//
-	// Collect the average screen space positions and interpolate towards it
-
-	// apply the summarized rotation to the yaw of the player via interpolation
 	FRotator ControllerRotation = PlayerController->GetControlRotation();
-	ControllerRotation.Yaw = FMath::FInterpTo(ControllerRotation.Yaw, ControllerRotation.Yaw + SummarizedSpeed, FApp::GetDeltaTime(), 13.5f);
-	PlayerController->SetControlRotation(ControllerRotation);
+	CamRotationToTarget.Pitch = ControllerRotation.Pitch;
+	CamRotationToTarget.Roll = ControllerRotation.Roll;
+	PlayerController->SetControlRotation(UKismetMathLibrary::RInterpTo(ControllerRotation, CamRotationToTarget, FApp::GetDeltaTime(), 150.f));
```
Comment (louisgv) [inline Source/NujasCombat/Private/DynamicTargetingComponent.cpp]: Please use Fmath (Core) instead of KismetMath (BPLib). They are essentially the same:

https://docs.unrealengine.com/en-US/API/Runtime/Core/Math/FMath/RInterpTo/index.html

https://docs.unrealengine.com/en-US/API/Runtime/Engine/Kismet/UKismetMathLibrary/RInterpTo/index.html

Comment (louisgv) [reply Source/NujasCombat/Private/DynamicTargetingComponent.cpp]: Also please move the interpolation into a variable before the call, make code easier to follow.

Comment (DennisSSDev) [reply Source/NujasCombat/Private/DynamicTargetingComponent.cpp]: Substituted the Kismet functions as well as simplified line 195
